version: "1.1"
name: Status Check
env:
  host: vika.cn
tests:
  vika.cn:
    steps:
      - name: GET request
        http:
          url: https://vika.cn
          method: GET
          check:
            status: /^20/
  wp.vika.cn:
    steps:
      - name: GET request
        http:
          url: https://vika.cn?home=1
          method: GET
          check:
            status: /^20/
  integration.vika.ltd:
    steps:
      - name: GET request
        http:
          url: https://integration.vika.ltd
          method: GET
          check:
            status: /^20/
  aitable.ai:
    steps:
      - name: GET request
        http:
          url: https://aitable.ai
          method: GET
          check:
            status: /^20/