version: "1.1"
name: Status Check
env:
  host: vika.cn
tests:
  vika.cn:
    steps:
      - name: GET request
        http:
          url: https://vika.cn
          method: GET
          check:
            status: /^20/
  wp.vika.cn:
    steps:
      - name: GET request
        http:
          url: https://vika.cn?home=1
          method: GET
          check:
            status: /^20/
  bbs.vika.cn:
    steps:
      - name: GET request
        http:
          url: https://bbs.vika.cn
          method: GET
          check:
            status: /^20/
  integration.vika.ltd:
    steps:
      - name: GET request
        http:
          url: https://integration.vika.ltd
          method: GET
          check:
            status: /^20/
  apitable.com:
    steps:
      - name: GET request
        http:
          url: https://apitable.com
          method: GET
          check:
            status: /^20/