name: 'Broken Links Check'

on:
  schedule:
    - cron: 0 6 * * 1 # every week at 14:00pm UTC+8:00
  workflow_dispatch:

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan links
        id: scan-links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "https://vika.cn ,https://vika.cn/?home=1, https://apitable.com, https://vika.cn/pricing"
          config: .github/linkinator.config.json

      - name: Create new issue as bug report
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUMMARY_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/broken-links-check-issue-template.md
