name: 'Scan Developer Center Broken Links'

on:
  schedule:
    - cron: 0 6 * * 1 # every monday at 14:00pm UTC+8:00
  workflow_dispatch:

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan links
        id: scan-links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "https://vika.cn/developers, https://developers.apitable.com"
          config: .github/dc-linkinator.config.json

      - name: Create new issue as bug report
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUMMARY_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/dc-broken-link-issue-template.md
